### ISSUE TITLE
seeding class not foud in laravel5

### ISSUE THREAD

**Issue by falakHamid** [zeke8402/booking-app#12]
when i add seeding classes  in laravel5 by using command< php artisan db:seed> than i found an error
  
class ' BookingDates not found'
![error](https://cloud.githubusercontent.com/assets/12462261/8510813/887bfdac-2315-11e5-902b-f64919e42e44.png)

tell me how to remove this error

**Comment by zeke8402** [comment]
So, you're adding the seeding classes to a Laravel 5 project? 
Both the BookingDates and BookingTimes migrations have been deprecated in favor of BookingDateTimes, so you won't need those classes.

**Comment by falakHamid** [comment]
yes in laravel5. And thanx for help
