### ISSUE TITLE
Select Packages not working and Admin login not accessable

### ISSUE THREAD

**Issue by umairiftikhar-ca** [zeke8402/booking-app#15]
Hi, 
Hitting http://localhost:8000/ shows "Select Package", that means there are no packages in database and users as well, I've checked my db, there are tables with name "packages", "users" etc but they don't have any data.
What I did:
1- Cloned zeke8402/booking-app
2- installed Composer
3- Changed my Db credentials in app/database.php
4- Migrate DB with php artisan migrate

Site is loading fine but it's showing "Select Package", Moreover at url "http://localhost:8000/admin" I can't login with username "admin" and password "admin"
Kindly let know do you have any dummy data to be imported in these table and how to do that.

Thanks

**Comment by zeke8402** [comment]
Yes, run php artisan db:seed

**Comment by umairiftikhar-ca** [comment]
Great, that worked..
