### ISSUE TITLE
Allow User to view and set configuration variables

### ISSUE THREAD

**Issue by zeke8402** [zeke8402/booking-app#17]
With the new method of dictating availability, we will allow 15 or 30 minute intervals (in a table for extensibility). We need to create a configuration area for this as well as potential other configuration variables, and allow the user to view and set these (starting with time intervals).

**Comment by sopnopriyo** [comment]
currently, the time interval is 30 minutes , so is it hardcoded ? where did you define it ?

**Comment by zeke8402** [comment]
It is a manual database entry here:
https://github.com/zeke8402/booking-app/blob/master/database/seeds/TimeIntervalTableSeeder.php
I don't think I set an option to switch it, the app needs to be extended to support it here...
https://github.com/zeke8402/booking-app/blob/master/resources/views/admin/configuration.blade.php

I'm not actively developing the project, but if I can find time within the next few weeks to do it, I will update the issue.
