### ISSUE TITLE
Create Validator Class

### ISSUE THREAD

**Issue by zeke8402** [zeke8402/booking-app#2]
I am already doing one validation with the customer database during a booking, to check to see if the customer already exists in the database, and there is many more areas in the app that need to have validation performed on them. This is going to get messy really fast, so a validator class will need to be implemented in the near future.

**Comment by zeke8402** [comment]
I will add a validator library I found to the project for this issue. It will validate the form before submission and output any errors.

**Comment by bc110402922** [comment]
hi can i use mysql, what i change in that? code..

**Comment by zeke8402** [comment]
Specify your connection type in app/config/database.php, you should be able to use whatever you like (thats supported by Laravel) as I don't believe I use any functions specific to one database.

**Comment by bc110402922** [comment]
dear you mean just change , you are using 'default' => 'sqllite',  and i replace it, with this. 

'default' => 'mysql', 
that's it ?
booking name of Db, i make it, in the php myadmin
then i run these commands 
php artisan migrate:rollback
php artisan migrate
regards
waiting

**Comment by zeke8402** [comment]
Yeah but below 'default' make sure your MySQL db has the correct credentials. I
tested this with MySQL so I know it works :)

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.4.2&pv=8.3]
On Thu, Jul 2, 2015 at 4:34 PM, zeke8402/booking-app
<reply@reply.github.com>
wrote:
dear you mean just change , you are using 'default' => 'sqllite', and i replace
it, with this.

'default' => 'mysql',
that's it ?
booking name of Db, i make it, in the php myadmin
then i run these commands
php artisan migrate:rollback
php artisan migrate
regards
waiting

—
Reply to this email directly or view it on GitHub
[https://github.com/zeke8402/booking-app/issues/2#issuecomment-118174083] .[https://github.com/notifications/beacon/ABmABT-NpccqDgiUe3CMUK_PPsoUAxXUks5oZaXngaJpZM4CIhjR.gif]

**Comment by bc110402922** [comment]
'default' => 'sqlite', replace with  'default' => 'mysql',
its not working with  when i replace, dear i am student please tell me in detail m  right now i change in daatabse.php file, and change in just line number 29 'default' => 'sqlite', i just created  booking name of database in mysql . but still data is not show in the DB, 
regards

**Comment by zeke8402** [comment]
Right below that line, you need to actually define where your database is and give Laravel the right credentials, so you need to do something like this

```
'mysql' => array(
			'driver'    => 'mysql',
			'host'      => 'localhost',
			'database'  => 'booking',
			'username'  => 'root',
			'password'  => 'password',
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
			'port'		=> '8889',
		),
```
You need to replace the host with wherever your database is, give it the correct username and password (user root, password password _not_ recommended :P), and the correct port, then it wil work.

Good luck
