### ISSUE TITLE
Upgrade to laravel 5.3

### ISSUE THREAD

**Issue by sopnopriyo** [zeke8402/booking-app#20]
Hello @zeke8402 ,

I have upgraded this project to laravel 5.3 with fixing some minor issues. If you want to have a look let me know .

Thanks,
Shahin

**Comment by zeke8402** [comment]
Sounds great! I'd love to check that out for sure.

**Comment by sopnopriyo** [comment]
Thanks for your response. Please find the pull request in the link bellow.

https://github.com/zeke8402/booking-app/pull/21

Thanks
