### ISSUE TITLE
Is there a demo?

### ISSUE THREAD

**Issue by jak-kal** [zeke8402/booking-app#23]
Looks great buddy! I'm a bit short on time so just wondered if you had a demo available.

Thanks in advance.

**Comment by zeke8402** [comment]
Sorry I do not. However if you're in the market for a booking app I'd recommend https://github.com/timegridio/timegrid as they not only have a live demo but a lot more features, and is more up to date.

**Comment by jak-kal** [comment]
I'll check it out - much appreciated!
